#!/usr/bin/env python3
"""Theme page conversion playbook — full guide to building & monetizing theme pages."""

THEME_PAGE_GUIDE = {
    "WHAT IS A THEME PAGE": [
        "A theme page is an account built around a TOPIC, not a personal brand",
        "Examples: @MotivationDaily, @CuteDogs, @TechTips, @LuxuryLifestyle, @FitnessMemes",
        "No face required — you curate and repost content from creators with permission",
        "Theme pages can hit 100K+ followers in 3-6 months with consistent effort",
        "Monetization starts at 10K followers and scales dramatically past 100K",
        "The strategy: build authority in a niche, then convert that attention into income",
    ],
    "STEP 1 — CHOOSE YOUR NICHE": {
        "The Golden Triangle (pick 2 of 3)": [
            "HIGH PASSION — you genuinely enjoy consuming this content",
            "HIGH DEMAND — large audience already exists (check competitor follower counts)",
            "HIGH CPM / MONETIZATION POTENTIAL — brands want to reach this audience",
        ],
        "Best-Performing Niches in 2024-2025": [
            "Finance / Wealth / Business (highest CPM — $20-50 per 1000 views)",
            "Health / Fitness / Wellness (evergreen, massive audience)",
            "Motivation / Mindset (insane shareability, goes viral easily)",
            "Luxury / Real Estate / Cars (aspirational content = high engagement)",
            "Tech / AI / Software (fastest growing segment, tech-savvy audience)",
            "Beauty / Fashion / Aesthetics (highly visual, strong brand deals)",
            "Food / Recipes / Cooking (universal appeal, sticky audience)",
            "Pets / Animals (highest organic reach of ANY niche — algorithm loves it)",
            "Travel / Adventure (aspirational, strong affiliate opportunities)",
            "True Crime / Dark History (obsessive niche — highest retention times)",
            "Relationships / Dating Advice (emotional content = shares and saves)",
            "Parenting / Family (huge demographic, underserved by creators)",
        ],
        "How to Validate Your Niche": [
            "Find 5 competitors with 100K+ followers — if they exist, the niche is proven",
            "Check if brands advertise in the niche (Instagram Explore ads = $ opportunity)",
            "Search the hashtag on TikTok — high view counts = active audience",
            "Look at affiliate marketplaces (ClickBank, ShareASale) — products in niche = money",
        ],
    },
    "STEP 2 — BUILD YOUR BRAND IDENTITY": {
        "Username Formula": [
            "Keep it short (under 15 characters), memorable, and niche-relevant",
            "Formula 1: [Niche] + [Power word] = @MotivationEmpire, @FitnessFuel, @TechVault",
            "Formula 2: [Emotion] + [Niche] = @DailyInspire, @CryptoInsider, @LuxuryVibes",
            "Formula 3: [Number/Frequency] + [Niche] = @DailyDoses, @1000Habits, @60SecondFit",
            "Check availability across TikTok, Instagram, YouTube, Twitter before committing",
        ],
        "Visual Identity": [
            "Profile photo: simple logo, icon, or aesthetic image (NO generic stock photos)",
            "Color palette: 2-3 colors max, consistent across ALL content",
            "Font: choose 1-2 fonts and NEVER deviate (Canva's brand kit makes this easy)",
            "Logo: create in Canva free or hire on Fiverr for $10-30",
            "Video aesthetic: consistent filter, frame style, or overlay that brands your content",
        ],
        "Content Pillars (3-5 Pillars Max)": [
            "Every post should fit into one of your 3-5 content pillars",
            "Example for Motivation page: Quotes, Success Stories, Daily Challenges, Business Tips, Mindset Shifts",
            "Example for Fitness page: Workouts, Nutrition, Transformation, Science, Products",
            "Consistent pillars train your audience to know what to expect",
            "They also train the algorithm to categorize and distribute your content correctly",
        ],
    },
    "STEP 3 — CONTENT SOURCING & CURATION": {
        "Sources for Repost Content": [
            "Reddit (r/[niche]) — goldmine of high-engagement content, often uncredited",
            "Pinterest — search your niche for viral images and quote graphics",
            "YouTube — download clips using yt-dlp, credit the creator in caption",
            "TikTok — stitch/duet viral content or use the creator's sound with your overlay",
            "Twitter/X — screenshot viral tweets with high engagement",
            "Unsplash / Pexels — free stock photos for graphic posts",
            "Google Alerts — set alerts for your niche keywords to find news",
        ],
        "Permission & Credit Rules": [
            "ALWAYS credit the original creator in your caption or video",
            "DM creators before reposting their full videos — most say yes (it's free promotion)",
            "If denied: use clips under 15 seconds with commentary (Fair Use principle)",
            "Never repost without credit — getting reported kills your account",
            "Build relationships with creators — they become your content partners",
        ],
        "Original Content Mix": [
            "Aim for 70% curated + 30% original content minimum",
            "Original content types that work WITHOUT showing your face:",
            "  - Quote graphics over aesthetic backgrounds",
            "  - Voiceover commentary on other people's videos (stitch/duet)",
            "  - Screen recordings of apps, websites, stats, tweets",
            "  - Text-based videos (CapCut/After Effects templates)",
            "  - AI-generated images with your voiceover or text overlay",
            "  - Slideshow/carousel posts of curated knowledge",
        ],
        "Content Batch Creation System": [
            "Dedicate 1 day/week to batch creating 7-21 pieces of content",
            "Use Canva bulk-create for quote graphics (20 posts in 30 minutes)",
            "Use CapCut templates — drop your footage in, done in 2 minutes per video",
            "Schedule with Later, Buffer, or TikTok's native scheduler",
            "Keep a content bank of 30+ pieces at all times — never scramble for ideas",
        ],
    },
    "STEP 4 — THE POSTING SYSTEM": {
        "Phase 1 — Launch Phase (Days 1-30)": [
            "Post 3-5 times per DAY on TikTok (algorithm rewards new accounts that flood it)",
            "Post 1-2 Reels per day on Instagram",
            "Post 1 YouTube Short + 1 Long-form per week",
            "Don't delete underperforming posts for at least 72 hours — TikTok slow-burns",
            "Reply to every single comment for the first 30 days",
            "Follow 20-50 accounts in your niche daily (follow-back strategy for early momentum)",
        ],
        "Phase 2 — Growth Phase (Days 30-90)": [
            "Reduce to 2-3x/day TikTok as you identify what content performs best",
            "Double down on your top-performing content formats",
            "Start 1-2 Lives per week (TikTok gives massive reach boost to live creators)",
            "Begin collaborating with similar-sized theme pages (shoutout-for-shoutout)",
            "Test different posting times to find YOUR audience's peak hours",
        ],
        "Phase 3 — Scale Phase (90+ days)": [
            "Start repurposing: every TikTok → Instagram Reel → YouTube Short",
            "Hire a VA ($3-10/hr) to handle scheduling and comment replies",
            "Build an email list from your bio link — your list is the only thing you OWN",
            "Start testing monetization methods systematically",
        ],
    },
    "STEP 5 — VIRALITY FORMULA": {
        "Hook Formula (First 3 Seconds)": [
            "SHOCK: 'I made $50,000 in 30 days from a theme page...'",
            "QUESTION: 'Why do the rich keep THIS a secret?'",
            "CONTRAST: 'Most people waste 8 hours/day. Here's what successful people do instead:'",
            "STORY: 'I was broke 6 months ago. Then I found this strategy.'",
            "VISUAL: Show the most visually interesting part of your video FIRST, explain after",
        ],
        "What Makes Content Go Viral": [
            "EMOTION: Content that makes people feel (inspired, shocked, amused, angry) gets shared",
            "RELATABILITY: 'This is literally me' = shares and saves",
            "UTILITY: 'I didn't know I needed this' = saves",
            "SOCIAL CURRENCY: Content that makes the sharer look smart, cool, or insightful",
            "NOVELTY: Information or perspective they've genuinely never seen before",
            "COMMUNITY: Content that speaks to a specific identity ('Every programmer will understand this')",
        ],
        "Hashtag Strategy for Virality": [
            "3-5 hashtags is the sweet spot (TikTok and Instagram's own recommendation)",
            "Always include 1 mega hashtag (#Motivation, #Fitness, #Tech) for broad distribution",
            "Always include 1-2 niche hashtags (e.g., #MorningRoutineMotivation) for targeted reach",
            "Add 1 trending hashtag from the Discover page when relevant",
            "Use unique hashtag combinations per post — don't duplicate exact sets",
        ],
        "Sound/Music Strategy": [
            "TikTok ranks content using trending sounds MUCH higher than non-trending sounds",
            "Check the Discover > Sounds tab for sounds trending in the last 7 days",
            "Use sounds with 10K-500K videos (not yet peaked, growing fast)",
            "Original audio you create can trend if your video goes viral first",
            "For Instagram Reels: use songs trending in Reels audio library",
        ],
    },
    "STEP 6 — MONETIZATION METHODS": {
        "Tier 1 — 1K to 10K Followers": [
            "Affiliate Marketing: Sign up for Amazon Associates, ShareASale, ClickBank",
            "  → Add affiliate links in bio, mention products naturally in content",
            "  → Potential: $100-$1,000/month depending on niche",
            "Merch: Sell print-on-demand products via Printful/Printify + Shopify (no inventory)",
            "Digital Products: $7-$27 PDF guides, templates, notion pages",
            "  → Example: 'The 30-Day Fitness Challenge Tracker' = $9 PDF = passive income",
        ],
        "Tier 2 — 10K to 100K Followers": [
            "Brand Deals / Sponsorships: DM brands in your niche directly",
            "  → Rate formula: $10-$50 per 1,000 followers for a sponsored post",
            "  → Create a media kit (follower count, engagement rate, audience demographics)",
            "TikTok Creator Fund: $0.02-$0.04 per 1,000 views (not the main income — just a bonus)",
            "TikTok LIVE Gifts: Fans send virtual gifts during live streams (converted to cash)",
            "Instagram Subscriptions: Charge $0.99-$99/month for exclusive content",
            "YouTube Partner Program: Join at 1,000 subs + 4,000 watch hours",
            "  → Ad revenue: $1-$30 per 1,000 views depending on niche",
        ],
        "Tier 3 — 100K+ Followers": [
            "Premium Brand Deals: $500-$10,000+ per sponsored post at this level",
            "Course Creation: Package your expertise into a $97-$997 course",
            "Coaching/Consulting: 1:1 or group coaching at $200-$2,000/session",
            "Newsletter Monetization: Grow an email list and sell to sponsors ($20-$50 per 1,000 subs)",
            "Community Memberships: Patreon, Skool, Discord ($9-$49/month)",
            "Agency Model: Manage social media for brands using YOUR proven system",
            "Account Flipping: Grow theme pages to 50K-100K and sell for $1,000-$20,000+",
        ],
        "Account Flipping (Fastest Cash Method)": [
            "WHAT: Build theme pages quickly, grow them to 50K-100K, then sell them",
            "WHERE to sell: Flippa.com, FameSwap.com, Social Tradia, direct to buyers",
            "PRICE: Accounts typically sell for 12-24x monthly revenue, or $10-$30 per 1,000 followers",
            "Example: 50K TikTok account in fitness niche → $500-$2,500 sale price",
            "Example: 100K Instagram account earning $500/month → sell for $6,000-$12,000",
            "TIMELINE: An experienced operator can flip a page in 60-90 days",
        ],
    },
    "STEP 7 — ANALYTICS & OPTIMIZATION": {
        "Key Metrics to Track Weekly": [
            "Follower growth rate (target: 10-20% weekly growth in early stages)",
            "Average views per post (is it trending up or down?)",
            "Engagement rate = (likes + comments + shares) / views × 100 (target: 5%+)",
            "Best-performing post of the week — replicate its format, topic, or style",
            "Worst-performing post — identify what to stop doing",
            "Profile visit rate — high visits but low follows = fix your profile/bio",
            "Link-in-bio click rate — low clicks = weak or unclear CTA",
        ],
        "When to Pivot vs. Double Down": [
            "If a content format gets 2x your average views: create 10 more IMMEDIATELY",
            "If a topic gets 5x+ views on first attempt: that's your golden content category",
            "If follower growth stalls for 2 weeks: test a new content format or posting time",
            "If engagement drops suddenly: check if you've been shadowbanned (post a comment and see if visible)",
            "Never make decisions on 1-2 posts — look at patterns across 10-20 posts",
        ],
    },
    "STEP 8 — AUTOMATION & SCALING": {
        "Tools That 10x Your Output": [
            "Canva Pro ($13/mo) — bulk create graphics, brand kit, resize for every platform",
            "CapCut (free) — viral video templates, auto-captions, AI features",
            "Later or Buffer ($15-25/mo) — schedule all platforms in advance",
            "Opus Clip (free tier) — AI clips long videos into 10 viral shorts automatically",
            "ElevenLabs (free tier) — AI voiceover for faceless content",
            "MidJourney / DALL-E — generate original images for your content",
            "ChatGPT/Claude — generate captions, hooks, content ideas at scale",
        ],
        "The Delegation Stack (When to Hire)": [
            "VA #1 at 10K followers: Comment management + content scheduling ($3-5/hr on Fiverr)",
            "VA #2 at 50K followers: Content research + repurposing ($5-10/hr)",
            "Video Editor at 100K+ followers: Full video editing ($50-200/video)",
            "Media Buyer at $5K/month: Paid promotion for fastest growth ($500-1,500/month)",
        ],
        "Multi-Platform Distribution System": [
            "Film ONE piece of content → distribute to 6+ platforms",
            "TikTok (original post) → Instagram Reels → YouTube Shorts → Twitter/X → Pinterest → LinkedIn",
            "IMPORTANT: Remove TikTok watermark before posting to Instagram/YouTube",
            "  Use SnapTik.app, SSSTikTok, or CapCut's own export to remove watermark",
            "Repurpose long YouTube videos into 10+ TikTok/Reel clips using Opus Clip",
            "Turn viral posts into carousel posts (5-10 slides) for Instagram saves",
        ],
    },
    "COMMON MISTAKES TO AVOID": [
        "Choosing a niche you don't consume yourself — you'll run out of ideas fast",
        "Quitting before 90 days — most accounts break through between days 60-120",
        "Posting inconsistently — 1 post/week will NEVER grow a theme page",
        "Using the exact same hashtags on every post — algorithm penalizes this",
        "Deleting posts after 24 hours — TikTok can push old content 30-60 days later",
        "Ignoring comments — engagement in comments is the #1 signal to algorithms",
        "Posting without a hook — the first 3 seconds determine if anyone watches",
        "Not putting a link in bio from Day 1 — you're leaving money on the table",
        "Copying competitors exactly — get inspired but differentiate your angle",
        "Buying fake followers — destroys engagement rate and algorithm trust permanently",
        "Not tracking analytics — if you're not measuring, you're guessing",
        "Starting too many platforms at once — dominate ONE platform first, then expand",
    ],
    "30-DAY LAUNCH CHECKLIST": [
        "Day 1: Choose niche, validate with competitor research, claim username on all platforms",
        "Day 2: Create logo, choose color palette, write bio (use the bio template above)",
        "Day 3: Batch create first 15 pieces of content (mix of formats)",
        "Day 4: Set up scheduling tool (Later or Buffer), schedule first 5 posts",
        "Day 5-7: Post 3-5x/day on TikTok, engage with 50 accounts in your niche",
        "Week 2: Identify your top 3 performing post formats and double down",
        "Week 2: Set up affiliate links and add to bio (start earning Day 1)",
        "Week 3: Start going LIVE 2x/week (TikTok), engage with trending content",
        "Week 3: Post your first YouTube Short (repurpose top TikTok)",
        "Week 4: Analyze all metrics, identify 3 things that work, eliminate what doesn't",
        "Week 4: Reach out to 5 similar-sized creators for shoutout-for-shoutout (SFS)",
        "Day 30: Audit your profile as a stranger — is your value prop clear? Does your bio convert?",
    ],
    "RESOURCES": {
        "Free Tools": [
            "Canva (canva.com) — graphics and video templates",
            "CapCut (capcut.com) — video editing with viral templates",
            "ChatGPT (chat.openai.com) — caption and hook generation",
            "SnapTik (snaptik.app) — TikTok watermark remover",
            "Opus Clip (opus.pro) — AI video repurposing",
            "Later (later.com) — social scheduling (limited free tier)",
        ],
        "Learning Resources": [
            "Study accounts with 100K+ in your niche — reverse-engineer their best posts",
            "TikTok Creator Academy (free inside TikTok) — algorithm education",
            "YouTube Creator Academy (free) — deep YouTube growth strategy",
            "Meta Blueprint (free) — official Instagram and Facebook growth courses",
        ],
        "Income Platforms": [
            "ClickBank (clickbank.com) — affiliate products in any niche",
            "Amazon Associates (affiliate-program.amazon.com) — promote any Amazon product",
            "ShareASale (shareasale.com) — high-paying physical and digital products",
            "FameSwap (fameswap.com) — buy and sell social accounts",
            "Flippa (flippa.com) — marketplace for digital assets including social accounts",
            "Gumroad (gumroad.com) — sell digital products directly to your audience",
        ],
    },
}
